# Generated by Django 3.1.5 on 2021-02-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210201_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('article', 'category'), name='article_category'),
        ),
    ]
