# Generated by Django 3.1.5 on 2021-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210226_2233'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationship',
            name='article_category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.Category'),
        ),
    ]
